# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomURLs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('random_url', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
